proyecto1/urls.py
import debug_toolbar
from django.conf import settings
from django.urls import include, path
from django import urls, views
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from catalogo.views import AuthorDetailView, AuthorListView, BookDetailView, DeleteAuthor, ModifyAuthor, indice, BookListView,contacto,SearchResultsListView,create_author,ModifyAuthor, DeleteAuthor #crearemos una vista indice para poder importarla y utilizarla en patterns

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('admin/', admin.site.urls),
    path('', indice, name ='indice'), # si no hay path, que meta la función que le vamos a definir nosotros para esa vista
    path('books', BookListView.as_view(), name='books'),
    path('book/<int:pk>', BookDetailView.as_view(), name='book-detail'),
    path('authors', AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', AuthorDetailView.as_view(), name='author-detail'),
    path('author/create', create_author, name='create_author'),
    path('author/modify/<int:pk>', ModifyAuthor.as_view(), name='modify_author'),
    path('author/delete/<int:pk>', DeleteAuthor.as_view(), name='delete_author'),
    path('contacto', contacto, name ='contacto'),
    path('search', SearchResultsListView.as_view(), name='search'),
]

catalogo/models.py
'''
0. Recuerda añadir app a installed apps en settings.py
1. Definir modelos
2. python manage.py migrate
'''
from django.db import models
from django.db.models.base import Model
from django.urls import reverse

class Genre(models.Model):
    name = models.CharField("Género",max_length=200)

    def __str__(self): #los métodos van SIEMPRE con self
         return self.name

class Author(models.Model):
    first_name = models.CharField('Nombre',max_length=100)
    last_name = models.CharField('Apellido',max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Muerte', null=True, blank=True)

    #ponemos NULL=True cuando los datos son "especiales" y necesitan tener algún valor

    def __str__(self):
        return self.first_name

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])
        
class Book(models.Model):
    '''Libro para aplicación de bibioteca...'''
    title = models.CharField(max_length=250)
    summary = models.TextField()
    isbn = models.CharField(max_length=13, blank=True) #si alguno de los campos puede estar vacío, hay que poner blank a true
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True, verbose_name='Autor') #AQUÍ NO TOCAMOS AUTHOR aunque queramos poner Autor de etiqueta
    fecha = models.DateField(blank=True, null=True,help_text='Fecha de publicacion') #auto_now lo ponemos para que coja una fecha por cada introducción de dato

    # Al tratarse de un campo como clave foránea, para mantener la integridad (on delete) establecemos null true
    # para que, aunque vayamos a crear un libro (si aún no está ese autor), siempre sea posible y se mantenga la integridad referencial.
    
    genre = models.ManyToManyField(Genre)

    def __str__(self): #Cuando hacemos print o mostramos un objeto, tira de este método
        return self.title

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('book-detail', args=[str(self.id)])

    def muestra_genero(self):
        '''Muestra genero para admin'''
        return ', '.join([gen.name for gen in self.genre.all()]) #recorre todos los géneros que tenga un libro

        #[gen.name for gen in self.genre.all()[:3]]) aquí sacaría solo los 3 primeros

    muestra_genero.short_description = 'Género'

    class Meta:
        verbose_name = 'Libro'

catalogo/forms.py
from django.forms import ModelForm
from catalogo.models import Author

class AuthorForm(ModelForm):
    '''
    Formulario para crear autores
    '''
    class Meta:
        model = Author
        fields = '__all__'
        

catalogo/views.py
from django.shortcuts import render,redirect #coge una plantilla y la devuelve
from django.views import generic
from catalogo.models import Author, Book
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from catalogo.forms import AuthorForm
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin

#from django.http import HttpResponse

# Create your views here.

def indice(request): #las funciones siempre tienen compo parámetro un request, una petición
    '''
    Página inicial de nuestra web
    '''

    datos = {'autor':'Luis Miguel'}
    busqueda = request.GET.get('q') #lanzaremos sobre mis libros para ver cuál tienen esa palabra
    if busqueda: 
        libros = Book.objects.filter(title__icontains=busqueda)
    else: #si GET es falso (none) entonces sigue con lo que había
        libros = Book.objects.all()

    datos ['libros'] = libros 
    return render(request, 'index.html', context=datos) #y siempre hay que responder con algo, una plantilla por lo general

def contacto(request): #las funciones siempre tienen compo parámetro un request, una petición
    '''
    Página de contacto de nuestra web
    '''
    return render(request, 'contacto.html')

#TODO LO QUE TIENE QUE VER CON LIBRO

class BookListView(generic.ListView):
    """Generic class-based view for a list of books."""
    model = Book
    template_name = 'book_list.html'
    paginate_by = 5
 
class BookDetailView(generic.DetailView):
    """Generic class-based detail view for a book."""
    model = Book
    template_name = 'book_detail.html'

#TODO LO QUE TIENE QUE VER CON AUTOR

class AuthorListView(generic.ListView):
    model = Author
    template_name = 'authors_list.html'
    queryset = Author.objects.all().order_by('last_name', 'first_name')

 
class AuthorDetailView(generic.DetailView):
    model = Author
    template_name = 'author_detail.html'

def create_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Autor creado.')
            return redirect('/')
    else:
        form = AuthorForm()
    datos = {'form': AuthorForm()}
    return render(request, 'create_author.html', 
        context=datos)

# Creación de autor con CreateVio. Añadimos SuccessMesaageMixin para mensaje de éxito.
class ModifyAuthor(SuccessMessageMixin, generic.UpdateView):
    model = Author
    fields = '__all__'
    template_name = 'modify_author.html'
    success_url = '/'
    success_message = "%(first_name)s %(last_name)s se ha modificado correctamente"


# Creación de autor con CreateVio. Añadimos SuccessMesaageMixin para mensaje de éxito.
class DeleteAuthor(SuccessMessageMixin, generic.DeleteView):
    model = Author
    template_name = 'delete_author.html'
    success_url = '/'
    success_message = "El autor se ha borrado correctamente"

    def delete(self,request,*args,**kwargs):
        messages.success(self.request,self.success_message)
        return super(DeleteAuthor, self).delete(request, *args, **kwargs)

#Este search es mío
class SearchResultsListView(ListView):
    model = Book
    context_object_name = 'book_list'
    template_name = 'search.html'
    def get_queryset(self): # new
        query = self.request.GET.get('q')
        if not query:
            query=""
        else:
            return Book.objects.filter(title__icontains=query)
    

catalogo/templates/author_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>Nombre completo: {{ author.first_name }} ({{ author.last_name }})</h1>

  <p><strong>Nombre:</strong> <a href="">{{ author.first_name }}</a></p>
  <p><strong>Apellido:</strong> {{ author.last_name }}</p>
  <p><strong>Fecha de nacimiento:</strong> {{ author.date_of_birth }}</p>
  <p><strong>Fecha de defunción:</strong> {{ author.date_of_death }}</p>
{% endblock %}

catalogo/templates/authors.html
{% extends "base.html" %}

{% block title %}Autores{% endblock %}

{% block content %}

<h1>Lista de autores</h1>

<ul>
    {% for author in authors%}
    <li>{{author.first_name}} {{author.last_name}}</li>
    {% endfor %}
</ul>



{% endblock %}

catalogo/templates/authors_list.html
{% extends "base.html" %}

{% block content %}
<h1>Lista de autores en detalle</h1>
{% if author_list %}
<ul>
  {% for author in author_list %}
  <li><a href={% url 'modify_author' author.id %}><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
        fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
        <path
          d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z" />
      </svg></a> <a href={% url 'delete_author' author.id %}><svg xmlns="http://www.w3.org/2000/svg" width="16"
        height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
        <path
          d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
        <path fill-rule="evenodd"
          d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
      </svg><a href="{{ author.get_absolute_url }}">{{ author.first_name }}</a> ({{ author.last_name }})
      {% endfor %}
</ul>
{% else %}
<p>No hay autores en la biblioteca.</p>
{% endif %}

<hr>
<h5><a href="{% url 'create_author' %}">Crear Autor</a></h5>





{% endblock %}

catalogo/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Proyecto Django</title>

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
    integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
</head>
<nav class="navbar navbar-dark bg-dark">
  <div class="container">

    <a class="navbar-brand" href="#">
      <img src="" width="30" height="30" class="d-inline-block align-top" alt="" href="{% url 'indice' %}">
      Mi Superbiblioteca
    </a>

    <button class="navbar-toggler border-0" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
      aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse text-center justify-content-lg-end" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link small" href="{% url 'indice' %}">
          Home
        </a>
        <a class="nav-item nav-link small" href="{% url 'books' %}">
          Libros
        </a>
        <a class="nav-item nav-link small" href="{% url 'authors' %}">
          Autores
        </a>
        <a class="nav-item nav-link small" href="{% url 'contacto' %}">
          Contacto
        </a>
        <a class="nav-item nav-link small" href="{% url 'search' %}">
          Search
        </a>
        <a class="nav-item nav-link small" style="align-self: center;" href="#">

          <form class="form-inline mt-2 mt-md-0" action="/search" method="get">
            <!--ACTION redirige-->
            <input name="q" class="form-control mr-sm-2" type="text" placeholder="Introduce palabra título"
              aria-label="Search">
          </form>
        </a>
      </div>
    </div>
  </div>
</nav>
<!-- /Nav -->
<!-- Body -->

<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-10 ">
        {% if messages %}
        <ul class="messages">
          {% for message in messages %}
          <div class="alert {% if message.tags %} alert-{{ message.tags }}{% else %}alert-primary{% endif %}"
            role="alert">{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}

        {% block content %}{% endblock %}
      </div>
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
    crossorigin="anonymous"></script>
</body>
<!-- /Body -->
<!-- Pagination -->
{% block pagination %}
{% if is_paginated %}
<div class="pagination">
  <span class="page-links">
    {% if page_obj.has_previous %}
    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Anterior</a>
    {% endif %}
    <span class="page-current">
      Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
    </span>
    {% if page_obj.has_next %}
    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">Siguiente</a>
    {% endif %}
  </span>
</div>
{% endif %}
{% endblock %}

<!-- /Pagination -->

</html>

catalogo/templates/book_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>Título: {{ book.title }}</h1>

  <p><strong>Autor:</strong> <a href="">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Sumario:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Idioma:</strong> {{ book.language }}</p>
  <p><strong>Género:</strong> {{ book.genre.all|join:", " }}</p>
{% endblock %}

catalogo/templates/book_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Lista de libros en detalle</h1>
  {% if book_list %}
  <ul>
    {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>No hay libros en la biblioteca.</p>
  {% endif %}

  
{% endblock %}

catalogo/templates/books.html
{% extends "base.html" %}

{% block title %}Libros{% endblock %}

{% block content %}

<h1>Lista de libros</h1>

<ul>
    {% for libro in libros%}
    <!--Escribiendo {{libros}} sale el jQuery pero queda un poco marrullero-->
    <li>{{libro.title}}
        {% if libro.author %} <!--Si tiene autor, muéstralo. -->
        ({{libro.author.last_name}})
        {% endif %}</li>
    <!--pongo paréntesis porque quiero que lo muestre así, no es neceario en sintaxis-->
    {% endfor %}
</ul>



{% endblock %}

catalogo/templates/contacto.html
{% extends "base.html" %}

{% block content %}
<center>
  <br>
  <form action="https://formspree.io/f/mjvjljwd" method="POST">
    <label display: inline-block;>
      Tu email:
      <input type="email" name="_replyto">
    </label>
    <br>

    <label display: inline-block;>
      Tu mensaje:
      <textarea name="message"></textarea>
    </label>
    <br>
    <button type="submit">Enviar</button>
  </form>
</center>
{% endblock %}

catalogo/templates/create_author.html
{% extends "base.html" %}

{% block content %}

<h3>Crear nuevo autor:</h3>

<form action="" method="post"><!--Deja action en blanco para con una misma dirección poder hacer dos cosas: GET y POST -->

    {% csrf_token %} <!--OBLIGATORIO SIEMPRE en POST-->
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Enviar" />

</form>
{% endblock %}

catalogo/templates/delete_author.html
{% extends "base.html" %}

{% block content %}

<h1>Eliminar autor</h1>

<p>¿Está seguro de que quiere eliminar el autor: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Sí, eliminar.">
</form>

{% endblock %}

catalogo/templates/index.html
{% extends "base.html" %}

{% block title %}Mi superbiblio{% endblock %}

{% block content %}

<h1>Índice del Catálogo</h1>

{{autor}}

<h2 class="mt-4">Últimos libros</h2>
<ul>
    {% for libro in libros%}
    <!--Escribiendo {{libros}} sale el jQuery pero queda un poco marrullero-->
    <li>{{libro.title}}
        {% if libro.author %} <!--Si tiene autor, muéstralo. -->
        ({{libro.author.last_name}})
        {% endif %}</li>
    <!--pongo paréntesis porque quiero que lo muestre así, no es neceario en sintaxis-->
    {% endfor %}
</ul>

{% endblock %}

catalogo/templates/modify_author.html
{% extends "base.html" %}

{% block content %}
  <h1>Modificar autor</h1>
    <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Modificar">
  </form>
{% endblock %}

catalogo/templates/search.html
{% extends "base.html" %}

{% block title %}Search{% endblock %}

{% block content %}

<form class="form-inline mt-2 mt-md-0" action="{% url 'search' %}" method="get">
    <input name="q" class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
</form>

{% if book_list %}
<br>
<h2>LISTA DE LIBROS BUSCADOS</h2>
<ul>
    {% for book in book_list %}
    <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
    </li>
    {% endfor %}
</ul>
{% else %}
<p>No hay libros en la biblioteca.</p>
{% endif %}

{% endblock %}